name: Black Widow Core CI/CD
on:
  - push
  - pull_request

env:
  IMAGE_TAG: ${{ secrets.CONTAINER_REGISTRY }}/${{ github.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and tag image
        run: docker build -t ${{ env.IMAGE_TAG }} .

      - name: Push image to container registry
        run: docker push ${{ env.IMAGE_TAG }}

  check:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_TAG }}

    steps:
      - name: Check code formatting
        run: |
          isort . --check
          black . --check

      - name: Static code analysis
        run: prospector .

  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_TAG }}
    steps:
      - name: Run unit tests
        run: ./scripts/unit-test.sh

      - name: Run integration tests
        run: ./scripts/integration-test.sh