name: Black Widow Core CI/CD
on:
  - push
  - pull_request

env:
  IMAGE_TAG: ${{ secrets.CONTAINER_REGISTRY }}:${{ github.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and tag image
        run: docker build -t ${{ env.IMAGE_TAG }} .

      - name: Push image to container registry
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Check code formatting
        run: docker run --rm -t ${{ env.IMAGE_TAG }} bash -c "isort . --check && black . --check"

      - name: Static code analysis
        run: docker run --rm -t ${{ env.IMAGE_TAG }} bash -c "prospector ."

      - name: Run unit tests
        run: docker run --rm -t ${{ env.IMAGE_TAG }} bash -c "/scripts/unit-test.sh"

      - name: Run integration tests
        run: docker run --rm -t ${{ env.IMAGE_TAG }} bash -c "/scripts/integration-test.sh"